### ISSUE TITLE
HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by anneke** [sindresorhus/urls-md#9]
Hi,

thank you for making this script! Unfortunately I get an error when I try to use it:

```
$ urls-md list-of-urls.txt
HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/usr/local/lib/node_modules/urls-md/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I went into the urls-md local directory (from my global install), and I ran `npm install` seperately. Once I did that and went back to run the above script again, I got the same error, but a file was created in my original directory (a `list-of-urls.md.txt`, which I find confusing, so perhaps I misunderstood the workings/goal of this module :) )

**Comment by anneke** [comment]
Additional note: yes I _did_ misunderstand what this does, sorry! The text document I was trying to do something with only contains a list of url's (each on a new line) that I wanted to download as seperate markdown files. I suppose that the different format of my text file caused the problem?

**Comment by sindresorhus** [comment]
Your use-case is indeed different than what this does. As for the error, it seems one of the links pointed to a non-existing site. The bug here is that this package should more gracefully handle that situation.

**Comment by anneke** [comment]
Thanks for the explanation @sindresorhus !
